[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Configurações otimizadas para Prisma no Railway
PRISMA_CLI_QUERY_ENGINE_TYPE = "library"
PRISMA_CLIENT_ENGINE_TYPE = "library"
