[build]
builder = "DOCKERFILE"
dockerfilePath = "telegramBot/Dockerfile"

[deploy]
startCommand = "python bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
PYTHON_VERSION = "3.11" 